### ISSUE TITLE
scikit-learn installation 

### ISSUE THREAD

**Issue by vetmohit89** [scottgroup/snoGloBe#1]
Hello, 

I have installed and tried with both version of scikit-learn but it giving me error. I am trying example data now. But it is not working (snoGlobe) [mbansal@login004 example]$ snoglobe.py snoRNA.fa  target.txt  target.gtf  /data/user/mbansal/AG_DKC1_rawdata/small_rna_seq/snoGlobe/snoGloBe/example/chromo_dir/ output.txt
Traceback (most recent call last):
  File "./snoGloBe/bin/snoglobe.py", line 428, in <module>
    prep_snoglobe()
  File "./snoGloBe/bin/snoglobe.py", line 382, in prep_snoglobe
    verbose=verbose, calc_intron=True)
  File "./snoGloBe/bin/snoglobe.py", line 222, in run_snoglobe
    make_pred(step, sno_file, target_file, chunksize, nb_threads, outfile, threshold)
  File "./snoGloBe/bin/predict_mp.py", line 77, in make_pred
    mdl = pickle.load(open(mdl_path, 'rb'))
ModuleNotFoundError: No module named 'sklearn.ensemble.gradient_boosting' this is the error when scikit-learn     1.0.2 

When I installed lower version I got following error:  ModuleNotFoundError: No module named 'sklearn.ensemble.gradient_boosting'

**Comment by SinhaI** [comment]
Hi,
I am getting **ImportError: cannot import name 'logsumexp'**  error when trying to run snoGloBe.
Initially, snoGloBe runs fine and creates a temp directory.
My python version is  3.6.15, and scikit-learn Version is 0.24.2.
I tried to update python and scikit-learn and encountered another error:
Python 3.12.1
scikit-learn Version: 1.5.1
**ModuleNotFoundError: No module named 'sklearn.ensemble.gradient_boosting'**
Any suggestions or comments are highly appreciated.

Thanks.

**Comment by SinhaI** [comment]
Hi again,

snoGloBe is running fine for me now using the following versions:
**Python: 3.6.15
scikit-learn: 0.21.3
scipy : 1.1.0**

Thanks.
